#!/usr/bin/env bash
# Publishes every public workspace package at its current version, plus the
# generated theme-* packages under packages/theme/dist-publish/.
#   - private packages are skipped
#   - pre-release versions (version contains '-') go to npm dist-tag "next"
#   - already-published versions fail on npm and are silently skipped
#
# Theme packages live under packages/theme/dist-publish/theme-*/ and are
# generated by `pnpm --filter @jupyter-kit/theme build`. The release workflow
# runs that build first; locally, run it manually before invoking this script.
#
# Intended to be called from the release workflow, but also usable locally
# if you have the appropriate npm auth configured.
set -uo pipefail

REPO_ROOT=$(cd "$(dirname "$0")/.." && pwd)
cd "$REPO_ROOT"

publish_dir() {
  local dir="$1"
  [ -f "$dir/package.json" ] || return 0

  local NAME VERSION IS_PRIVATE TAG
  NAME=$(node -p "require('./$dir/package.json').name")
  VERSION=$(node -p "require('./$dir/package.json').version")
  IS_PRIVATE=$(node -p "require('./$dir/package.json').private || false")

  if [ "$IS_PRIVATE" = "true" ]; then
    echo "::group::skip $NAME (private)"
    echo "::endgroup::"
    return 0
  fi

  TAG=""
  if [[ "$VERSION" == *-* ]]; then
    TAG="--tag next"
  fi

  echo "::group::publish $NAME@$VERSION $TAG"
  (cd "$dir" && pnpm publish --access public $TAG --no-git-checks --provenance) \
    || echo "  -> skipped (already published or publish failed)"
  echo "::endgroup::"
}

shopt -s nullglob

# Workspace packages.
for pkg_dir in packages/*/; do
  publish_dir "${pkg_dir%/}"
done

# Generated theme-* packages — `pnpm --filter @jupyter-kit/theme build` must
# have already run to populate dist-publish/. We hard-fail if it didn't, so a
# release never silently skips the @jupyter-kit/theme-* packages.
if [ ! -d packages/theme/dist-publish ]; then
  echo "::error::packages/theme/dist-publish/ not found — themes were never built. Run \`pnpm --filter @jupyter-kit/theme build\` first."
  exit 1
fi
for theme_dir in packages/theme/dist-publish/theme-*/; do
  publish_dir "${theme_dir%/}"
done
